services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=docker_db
      - DB_USER=docker_db_user
      - DB_PASS=root

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database
 
  database:
    image: postgres:14.6-alpine3.16
    environment:
      - POSTGRES_DB=docker_db
      - POSTGRES_USER=docker_db_user
      - POSTGRES_PASSWORD=root

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=docker_db
      - DB_USER=docker_db_user
      - DB_PASS=root
    links:
      - redis
    depends_on:
      - redis
      - database

  worker2:
    build:
      context: .
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=docker_db
      - DB_USER=docker_db_user
      - DB_PASS=root
    links:
      - redis
    depends_on:
      - redis
      - database

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower --loglevel=info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
